### ISSUE TITLE
v30

### ISSUE THREAD

**Issue by locustwei** [libyal/libscca#10]
How to convert VOLUME{%%} to a DOS path

**Comment by joachimmetz** [comment]
@locustwei can you first explain to me what you mean with "DOS path"

**Comment by locustwei** [comment]
Drive letter 
eg:  VOLUME{01d59b5a1941385c-a61962ce}\ABC.EXE to C:\ABC.EXE

**Comment by joachimmetz** [comment]
That path is dependent on the originating system did you check the Mounted Devices in the Windows Registry? Also see: https://winreg-kb.readthedocs.io/en/latest/sources/system-keys/Mounted-devices.html
