### ISSUE TITLE
Why are file paths escaped (\\) but device paths not (\)?

### ISSUE THREAD

**Issue by patatetom** [libyal/libscca#12]
hi Joachim,

to perfect/uniform libscca, I just noticed that the file path had changed between the last two versions of libscca at this date (eg. `Filename: 1 : \VOLUME{...}\WINDOWS\...` became `Filename: 1 : \\VOLUME{...}\\WINDOWS\\...`) but that the volume path had remained on its simple slash version (eg. `Device path : \VOLUME{...}`)

thanks for this lib, regards, lacsaP.

**Comment by joachimmetz** [comment]
anything that is known to be a file path (that can be UCS-2 + surrogates) is converted to the escaped variant. For "device paths" this is currently unknown given AFAIK only a limited set of characters are used to represent them.

**Comment by joachimmetz** [comment]
> whether in file explorer or in a command prompt, Windows refuses to name it that way : is it possible under Windows to create a file with the name sub/marine ?

there are many different aspects to this:

* the actual file system format
* the system-level API
* the application level, like Windows explorer or command prompt

The fact that the application level does not allows you to do something, does not exclude a system-level API or file system format. The text you highlight in the context of the blog post is an example to explain/highlight where ambiguity can surface.

**Comment by joachimmetz** [comment]
Considering this answered, closing.
