### ISSUE TITLE
Rust binding for libscca

### ISSUE THREAD

**Issue by janstarke** [libyal/libscca#14]
Hello,

We're using `libscca` in our tool to generate bodyfile-based timelines (<https://github.com/dfir-dd/dfir-toolkit/blob/main/doc/pf2bodyfile.md>). For this purpose we wrote Rust bindings for (a part of) the `libscca`-API, which are currently integral part of `dfir-toolkit` (<https://github.com/dfir-dd/dfir-toolkit/tree/main/src/scca>).

I can imagine that other rust developers also would like to use `libscca`. Do you have interest of integrating the Rust bindings in your library? That could be a separate crate.

Kind regards, Jan

**Comment by joachimmetz** [comment]
I currently have no plans or bandwidth to maintain Rust bindings. Also why use C in Rust? Doesn't this defeat the reason to use Rust in the first place?

**Comment by janstarke** [comment]
Yes, that is the case, but:

- using Rust doesn't guarantee good code quality or flawlessnes
- I don't think one should write new code if there is already some good working solution
- I was reading a lot of your code and I like it

The last night, I was informed about a pure Rust implementation and I will try it out.

**Comment by joachimmetz** [comment]
Thanks for the additional context. Makes sense, as long as these are conscious/deliberate trade-offs.

I'll close this issue, given that my bandwidth is too limited to maintain bindings for an additional techstack.
