### ISSUE TITLE
Self built pkg incompatible with MacOS Sonoma?

### ISSUE THREAD

**Issue by j-schmied** [libyal/libscca#15]
Hello,

I followed the building instructions from https://github.com/libyal/libscca/wiki/Building#using-macos-pkgbuild and successfully built the libs as well as pkg/dmg files. 

If I want to install it, however, I get the following error:
<img width="732" alt="Screenshot 2024-02-16 at 10 15 08" src="https://github.com/libyal/libscca/assets/20594028/d614526e-3866-4bc6-872f-9bd1efc4bcf1">

Are there any further steps that I missed apart from the ones described in the building manual? Or might it be due to an architecture (ARM) incompatibility? 

Device: MacBook Pro (2021, M1 Max)
OS: MacOS Sonoma (14.3.1)

Best regards,
Jannik

**Comment by joachimmetz** [comment]
Which version of XCode / pkgbuild did you use? Technically you are the "software manufacturer" given you built the package.

**Comment by joachimmetz** [comment]
No response from reporter, closing given this issue is toolchain related.
