### ISSUE TITLE
Wiki Documentation Update

### ISSUE THREAD

**Issue by PoorBillionaire** [libyal/libscca#3]
Greetings--

Thank you for your work on libscca - getting libscca-python uploaded to PyPI is a really nice touch.

I'm not sure if you're taking merge requests for Wiki documentation, but I took the liberty of cloning my own copy of libscca's Wiki and updating the Development.md page. It's my understanding that GitHub doesn't offer the normal 'pull' functionality for Wiki pages, which is a shame.

Anyway, my changes can be seen [here](https://github.com/PoorBillionaire/libsccm-wiki/blob/master/Development.md)

I used the PyPI repository to build pyscca locally, and would be interested in updating the building Wiki to reflect that process if you are open to assistance with the docs.

Hope this helps.

Adam

**Comment by joachimmetz** [comment]
Adam, thanks I'll definitely have a look at wiki changes and trying to merge them back in.

> It's my understanding that GitHub doesn't offer the normal 'pull' functionality for Wiki pages, which is a shame.

Luckily under the hood it uses git ;)

Know that the wiki pages actually are generated from templates by the following script:
https://github.com/libyal/libyal/blob/master/scripts/wiki-generate.py

pypi support is still work in progress.

**Comment by joachimmetz** [comment]
I'm closing this issue in favor of https://github.com/libyal/libyal/issues/10. So expect some gradual adjustments.

I'll not merge your changes 1-to-1 but they are definitely helpful for inspiration on how to improve the documentation. Thx again for the changes.
