### ISSUE TITLE
pyscca: how to I get the file_metrics data?

### ISSUE THREAD

**Issue by ta-b0** [libyal/libscca#7]
I want to use class `file_metrics()`.
How to use it in Python3?

class `file()` has `open()` method but class `file_metrics()` has not `open()` method. 
How to analyze specific prefetch file?

If possible, please write sample code...

**Comment by joachimmetz** [comment]
Did you try `help(pyscca.file)` as indicated here https://github.com/libyal/libscca/wiki/Python-development#also-see ?

Try:
```
scca_file.get_number_of_file_metrics_entries()
scca_file.get_file_metrics_entry()
```

**Comment by ta-b0** [comment]
Thank you for your reply!
