### ISSUE TITLE
SCCA 2008 hash algorithm example not working as expected?

### ISSUE THREAD

**Issue by crazyemod** [libyal/libscca#9]
Hy, 

I think the implementation of the SCCA 2008 hash algorithm like it is described in the documentation (section 5.3) doesn't work as expected. I tested the function with the path of the cmd.exe. The System is a Windows 10 Pro (Build 19041) machine.

- path of the cmd.exe: `C:\Windows\System32\cmd.exe`
- upper-case Windows device path: `\DEVICE\HARDDISKVOLUME2\WINDOWS\SYSTEM32\CMD.EXE`
- hash value, determined with the algorithm like it is described in the documentation: `DD237864`
- hash value, described in the filename and in the prefetch file it self: `4A81B364`

 I think this happens because step 3 of section 5.4. isn't currently implemented.

> 3. Convert the string into an UTF-16 little-endian stream without a byte-order-mark or an end-of-string character (2x 0-bytes)

The `ord()` function used to transform a character to an integer returns the Unicode  and not the UTF-16LE value of the character. This is the reason for the wrong hash value, that is returned by the function. 

I change the function in the following way and it seems that it works:

``` 
def scca_2008_hash_function(filename):
    """ Calculates the prefetch hash value with the SCCA 2008 hash algorithm
    
    :param filename: upper-case Windows device path
    :type filename: str 
    """
    filename = filename.encode("UTF-16LE")
    hash_value = 314159
    filename_index = 0
    filename_length = len(filename)
    while filename_index + 8 < filename_length:
        character_value = filename[filename_index + 1] * 37
        character_value += filename[filename_index + 2]
        character_value *= 37
        character_value += filename[filename_index + 3]
        character_value *= 37
        character_value += filename[filename_index + 4]
        character_value *= 37
        character_value += filename[filename_index + 5]
        character_value *= 37
        character_value += filename[filename_index + 6]
        character_value *= 37
        character_value += filename[filename_index] * 442596621
        character_value += filename[filename_index + 7]
        hash_value = ((character_value - (hash_value * 803794207)) % 0x100000000)
        filename_index += 8

    while filename_index < filename_length:
        hash_value = (((37 * hash_value) + filename[filename_index]) % 0x100000000)
        filename_index += 1

    return hash_value
```

Have a  nice day.:D

**Comment by joachimmetz** [comment]
`scca_2008_hash_function` is intended as an example of just the hash calculation. Filename is assumed to be already decoded and normalized.

**Comment by crazyemod** [comment]
A okay, the normalization should be added as hint in the documentation. Thanks for the reply.
